### ISSUE TITLE
Linear Search 

### ISSUE THREAD

**Issue by sudheerkumar0** [sudheerkumar0/HackToberfest-2022#2]
I want to create linear search in any language.

**Comment by Geetanjaligupta123** [comment]
Hii, I want to add linear search program in c++.
can you please assign this issue to me

**Comment by sudheerkumar0** [comment]
I am assigned you this issue @Geetanjaligupta123

**Comment by Geetanjaligupta123** [comment]
Ok

**Comment by zmwaris1** [comment]
I want to add linear search in python. Please let me.

**Comment by sudheerkumar0** [comment]
Ok work on it python @zmwaris1

**Comment by sudheerkumar0** [comment]
Complete issue
